apiVersion: v1
kind: Service
metadata:
  name: angular-web-app
spec:
  selector:
    app: angular-web-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-web-app
spec:
  selector:
    matchLabels:
      app: angular-web-app
  replicas: 5
  template:
    metadata:
      labels:
        app: angular-web-app
    spec:
      containers:
      - name: angular-web-app
        image: angular-web-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
